//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarQube.Plugins.Maven {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MavenResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MavenResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarQube.Plugins.Maven.MavenResources", typeof(MavenResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download the Maven dependency from {0}. The HTTP status code was {1} and the reason \&quot;{2}\&quot;&quot;.
        /// </summary>
        internal static string ERROR_FailedToDownloadDependency {
            get {
                return ResourceManager.GetString("ERROR_FailedToDownloadDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding dependencies for {0}.
        /// </summary>
        internal static string MSG_AddingDependenciesForPOM {
            get {
                return ResourceManager.GetString("MSG_AddingDependenciesForPOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to resolve dependency from parent POM: {0}.
        /// </summary>
        internal static string MSG_AttemptingToResolveFromParentPOM {
            get {
                return ResourceManager.GetString("MSG_AttemptingToResolveFromParentPOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency has already been visited: {0}.
        /// </summary>
        internal static string MSG_DependencyAlreadyVisited {
            get {
                return ResourceManager.GetString("MSG_DependencyAlreadyVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file from {0}....
        /// </summary>
        internal static string MSG_DownloadingFile {
            get {
                return ResourceManager.GetString("MSG_DownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded project variable: {0}.
        /// </summary>
        internal static string MSG_ExpandedProjectVariable {
            get {
                return ResourceManager.GetString("MSG_ExpandedProjectVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File downloaded to {0}.
        /// </summary>
        internal static string MSG_FileDownloaded {
            get {
                return ResourceManager.GetString("MSG_FileDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POM does not contain a jar. POM: {0}, Packaging: {1}.
        /// </summary>
        internal static string MSG_POMDoesNotContainAJar {
            get {
                return ResourceManager.GetString("MSG_POMDoesNotContainAJar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Maven dependency {0}.
        /// </summary>
        internal static string MSG_ProcessingDependency {
            get {
                return ResourceManager.GetString("MSG_ProcessingDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved version from &lt;dependencyManagement&gt;: {0}.
        /// </summary>
        internal static string MSG_ResolvedVersionFromDependencyManagement {
            get {
                return ResourceManager.GetString("MSG_ResolvedVersionFromDependencyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved dependency using info in parent POM {0}.
        /// </summary>
        internal static string MSG_ResolvedVersionInPom {
            get {
                return ResourceManager.GetString("MSG_ResolvedVersionInPom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping inherited dependency: {0}.
        /// </summary>
        internal static string MSG_SkippingInheritedDependency {
            get {
                return ResourceManager.GetString("MSG_SkippingInheritedDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping dependency {0}. Scope: {1}.
        /// </summary>
        internal static string MSG_SkippingScopedDependency {
            get {
                return ResourceManager.GetString("MSG_SkippingScopedDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using cached copy of {0}.
        /// </summary>
        internal static string MSG_UsingCachedFile {
            get {
                return ResourceManager.GetString("MSG_UsingCachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maven dependency was not found. Url: {0}..
        /// </summary>
        internal static string WARN_DependencyWasNotFound {
            get {
                return ResourceManager.GetString("WARN_DependencyWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolved dependency: {0}.
        /// </summary>
        internal static string WARN_FailedToResolveDependency {
            get {
                return ResourceManager.GetString("WARN_FailedToResolveDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The jar has already been added by another dependency. Current coordinate: {0}. Local path: {1}.
        /// </summary>
        internal static string WARN_JarAddedByAnotherDependency {
            get {
                return ResourceManager.GetString("WARN_JarAddedByAnotherDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized project variable: {0}.
        /// </summary>
        internal static string WARN_UnrecognizedProjectVariable {
            get {
                return ResourceManager.GetString("WARN_UnrecognizedProjectVariable", resourceCulture);
            }
        }
    }
}
