//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarQube.Plugins.Maven {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MavenResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MavenResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarQube.Plugins.Maven.MavenResources", typeof(MavenResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download the Maven artifact from {0}. The HTTP status code was {1} and the reason \&quot;{2}\&quot;&quot;.
        /// </summary>
        internal static string ERROR_FailedToDownloadArtifact {
            get {
                return ResourceManager.GetString("ERROR_FailedToDownloadArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file from {0}....
        /// </summary>
        internal static string MSG_DownloadingFile {
            get {
                return ResourceManager.GetString("MSG_DownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File downloaded to {0}.
        /// </summary>
        internal static string MSG_FileDownloaded {
            get {
                return ResourceManager.GetString("MSG_FileDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Maven artifact {0}.
        /// </summary>
        internal static string MSG_ProcessingArtifact {
            get {
                return ResourceManager.GetString("MSG_ProcessingArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using cached copy of {0}.
        /// </summary>
        internal static string MSG_UsingCachedFile {
            get {
                return ResourceManager.GetString("MSG_UsingCachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maven artifact was not found. Url: {0}..
        /// </summary>
        internal static string WARN_ArtifactWasNotFound {
            get {
                return ResourceManager.GetString("WARN_ArtifactWasNotFound", resourceCulture);
            }
        }
    }
}
