//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarQube.Plugins.Roslyn.CommandLine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CmdLineResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CmdLineResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarQube.Plugins.Roslyn.CommandLine.CmdLineResources", typeof(CmdLineResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Path/Url to Repo&gt; - overwrites default nuget behaviour and only uses this repository..
        /// </summary>
        internal static string ArgDesciption_CustomNuGetRepo {
            get {
                return ResourceManager.GetString("ArgDesciption_CustomNuGetRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indicates that you accept the licenses for any packages that required license acceptance.
        /// </summary>
        internal static string ArgDescription_AcceptLicenses {
            get {
                return ResourceManager.GetString("ArgDescription_AcceptLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NuGet package id&gt;[:&lt;version&gt;].
        /// </summary>
        internal static string ArgDescription_AnalzyerRef {
            get {
                return ResourceManager.GetString("ArgDescription_AnalzyerRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PathToOutputDirectory&gt; Specifies where the jar file should be put.
        /// </summary>
        internal static string ArgDescription_OutputDirectory {
            get {
                return ResourceManager.GetString("ArgDescription_OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for analyzers in target package and any dependencies.
        /// </summary>
        internal static string ArgDescription_RecurseDependencies {
            get {
                return ResourceManager.GetString("ArgDescription_RecurseDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path to rules xml file&gt;.
        /// </summary>
        internal static string ArgDescription_RuleXmlFile {
            get {
                return ResourceManager.GetString("ArgDescription_RuleXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path to sqale xml file&gt; - DEPRECATED. Use the /rules parameter instead..
        /// </summary>
        internal static string ArgDescription_SqaleXmlFile {
            get {
                return ResourceManager.GetString("ArgDescription_SqaleXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed NuGet reference. Id: {0}, version: {1}.
        /// </summary>
        internal static string DEBUG_ParsedReference {
            get {
                return ResourceManager.GetString("DEBUG_ParsedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using rules xml file &apos;{0}&apos;.
        /// </summary>
        internal static string DEBUG_UsingRuleFile {
            get {
                return ResourceManager.GetString("DEBUG_UsingRuleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid NuGet package version: {0}.
        /// </summary>
        internal static string ERROR_InvalidVersion {
            get {
                return ResourceManager.GetString("ERROR_InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet package id must be specified.
        /// </summary>
        internal static string ERROR_MissingPackageId {
            get {
                return ResourceManager.GetString("ERROR_MissingPackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified rules xml file could not found: {0}.
        /// </summary>
        internal static string ERROR_RuleFileNotFound {
            get {
                return ResourceManager.GetString("ERROR_RuleFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The /sqale parameter is no longer supported. 
        ///If you are targetting SonarQube v6.7 or higher, use the /rules parameter and add the debt remediation information to the rules.xml file instead. If you are targetting an older version of SonarQube, use v1.0 of this SDK.
        ///.
        /// </summary>
        internal static string ERROR_SqaleParameterIsNotSupported {
            get {
                return ResourceManager.GetString("ERROR_SqaleParameterIsNotSupported", resourceCulture);
            }
        }
    }
}
