//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roslyn.SonarQube {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roslyn.SonarQube.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded: {0} analysers..
        /// </summary>
        public static string AnalyzersLoadSuccess {
            get {
                return ResourceManager.GetString("AnalyzersLoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the assembly &apos;{0}&apos;. 
        ///
        ///Error: {1}.
        /// </summary>
        public static string AssemblyLoadError {
            get {
                return ResourceManager.GetString("AssemblyLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded assembly: {0}.
        /// </summary>
        public static string AssemblyLoadSuccess {
            get {
                return ResourceManager.GetString("AssemblyLoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: {0} pathToAnalyzerAssembly.
        /// </summary>
        public static string CommandLineUsage {
            get {
                return ResourceManager.GetString("CommandLineUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded analyser: {0}.
        /// </summary>
        public static string DEBUG_AnalyserLoaded {
            get {
                return ResourceManager.GetString("DEBUG_AnalyserLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist. Provide the path to an existing assembly.
        /// </summary>
        public static string ERR_ArgFileDoesNotExist {
            get {
                return ResourceManager.GetString("ERR_ArgFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information visit &lt;a href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;the rule&apos;s help page&lt;/a&gt;..
        /// </summary>
        public static string ForMoreDetailsLink {
            get {
                return ResourceManager.GetString("ForMoreDetailsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Details.
        /// </summary>
        public static string MoreDetailsTitle {
            get {
                return ResourceManager.GetString("MoreDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No analyzers found in assembly..
        /// </summary>
        public static string NoAnalysers {
            get {
                return ResourceManager.GetString("NoAnalysers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description was provided..
        /// </summary>
        public static string NoDescription {
            get {
                return ResourceManager.GetString("NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rules written to {1}.
        /// </summary>
        public static string SuccessOutputFile {
            get {
                return ResourceManager.GetString("SuccessOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation succeeded..
        /// </summary>
        public static string SuccessStatus {
            get {
                return ResourceManager.GetString("SuccessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping rule in analyzer {0}: Duplicate key..
        /// </summary>
        public static string WARN_DuplicateKey {
            get {
                return ResourceManager.GetString("WARN_DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate tag {0} on analyzer {1}.
        /// </summary>
        public static string WARN_DuplicateTags {
            get {
                return ResourceManager.GetString("WARN_DuplicateTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty description found for rule {0}. Placeholder description inserted..
        /// </summary>
        public static string WARN_EmptyDescription {
            get {
                return ResourceManager.GetString("WARN_EmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping rule in analyzer {0}: No key found..
        /// </summary>
        public static string WARN_EmptyKey {
            get {
                return ResourceManager.GetString("WARN_EmptyKey", resourceCulture);
            }
        }
    }
}
